- hosts: localhost
  gather_facts: false
  vars:
    ansible_source_directory: ./ansible
    destination_directory: /Users/alancoding/Documents/repos/content_collector/awx_modules
    collection_namespace: awx
    collection_name: awx
    source_sub_directory: /web_infrastructure/ansible_tower
  roles:
  - scaffold_directories
  - migrate_content
  - test_modules
  - galaxy_yml
